-- MySQL Script generated by MySQL Workbench
-- Wed Dec 22 22:41:15 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`groupe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`groupe` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nomGroupe` VARCHAR(25) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`offre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`offre` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lieuDep` VARCHAR(45) NOT NULL,
  `lieuArr` VARCHAR(45) NOT NULL,
  `PI` VARCHAR(45) NULL,
  `dateDep` DATE NOT NULL,
  `horrDep` TIME NOT NULL,
  `Prix` INT NOT NULL,
  `infoRdv` VARCHAR(45) NULL,
  `Contrainte` VARCHAR(45) NULL,
  `nbrPlace` INT NOT NULL,
  `utilisateurId` INT NOT NULL,
  `groupe_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_offre_utilisateur1_idx` (`utilisateurId` ASC),
  INDEX `fk_offre_groupe1_idx` (`groupe_id` ASC),
  CONSTRAINT `fk_offre_utilisateur1`
    FOREIGN KEY (`utilisateurId`)
    REFERENCES `mydb`.`utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_offre_groupe1`
    FOREIGN KEY (`groupe_id`)
    REFERENCES `mydb`.`groupe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`note`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`note` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `note` INT NULL,
  `utilisateurId1` INT NOT NULL,
  `utilisateurId2` INT NOT NULL,
  `offre_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_note_utilisateur1_idx` (`utilisateurId1` ASC),
  INDEX `fk_note_utilisateur2_idx` (`utilisateurId2` ASC),
  INDEX `fk_note_offre1_idx` (`offre_id` ASC),
  CONSTRAINT `fk_note_utilisateur1`
    FOREIGN KEY (`utilisateurId1`)
    REFERENCES `mydb`.`utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_note_utilisateur2`
    FOREIGN KEY (`utilisateurId2`)
    REFERENCES `mydb`.`utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_note_offre1`
    FOREIGN KEY (`offre_id`)
    REFERENCES `mydb`.`offre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`utilisateur` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `nom` VARCHAR(20) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `dateNaissance` DATE NOT NULL,
  `genre` VARCHAR(1) NOT NULL,
  `tel` INT NOT NULL,
  `siVoiture` BIT(1),
  `immatriculation` VARCHAR(25) NULL,
  `marque` VARCHAR(45) NULL,
  `modele` VARCHAR(45) NULL,
  `couleur` VARCHAR(45) NULL,
  `nbrPlace` INT NULL,
  `note_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_utilisateur_note1_idx` (`note_id` ASC),
  CONSTRAINT `fk_utilisateur_note1`
    FOREIGN KEY (`note_id`)
    REFERENCES `mydb`.`note` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`requete`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`requete` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` BIT(1) NULL,
  `message` VARCHAR(100) NULL,
  `offre_id` INT NOT NULL,
  `utilisateur_id` INT NOT NULL,
  `offre_id1` INT NOT NULL,
  PRIMARY KEY (`id`, `offre_id`, `utilisateur_id`, `offre_id1`),
  INDEX `fk_requete_offre1_idx` (`offre_id` ASC),
  INDEX `fk_requete_utilisateur1_idx` (`utilisateur_id` ASC),
  INDEX `fk_requete_offre2_idx` (`offre_id1` ASC),
  CONSTRAINT `fk_requete_offre1`
    FOREIGN KEY (`offre_id`)
    REFERENCES `mydb`.`offre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_requete_utilisateur1`
    FOREIGN KEY (`utilisateur_id`)
    REFERENCES `mydb`.`utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_requete_offre2`
    FOREIGN KEY (`offre_id1`)
    REFERENCES `mydb`.`offre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`utilisateur_has_groupe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`utilisateur_has_groupe` (
  `utilisateurId1` INT NOT NULL,
  `groupeId` INT NOT NULL,
  `utilisateurId2` INT NOT NULL,
  PRIMARY KEY (`utilisateurId1`, `groupeId`, `utilisateurId2`),
  INDEX `fk_utilisateur_has_groupe_groupe1_idx` (`groupeId` ASC),
  INDEX `fk_utilisateur_has_groupe_utilisateur_idx` (`utilisateurId1` ASC),
  CONSTRAINT `fk_utilisateur_has_groupe_utilisateur`
    FOREIGN KEY (`utilisateurId1`)
    REFERENCES `mydb`.`utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_utilisateur_has_groupe_groupe1`
    FOREIGN KEY (`groupeId`)
    REFERENCES `mydb`.`groupe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
